### PR TITLE
Polynomial arithmetic in DFT/FFT/NTT and coefficient representations

### PR DESCRIPTION
**Pull request by JL2718**
naive O(n^2) DFT, in-place O(n log n) FFT, and some changes to Mersenne31Complex to enable inversion without a type-specific implementation

Completed:
- Implementation of cyclic polynomial quotient ring to test multiplication via fft vs naive
- type system and abstractions for polynomials
- tests on complex M31 and new simple field type Fp17

### CODE REVIEW

**Comment by JL2718** [comment]
Now includes a cyclic polynomial implementation to use for multiplication. Can use fft, dft, or coefficient multiplication.  As in this test:
```rust
    #[test]
    fn test_fft_mul_random_full(){
        let mut rng = rand::thread_rng();
        let mut aa:PC = rng.gen();
        let mut bb:PC = rng.gen();
        let cc = aa*bb;
        let dd = (aa.fft()*bb.fft()).ifft();
        assert_eq!(cc,dd);
    }
```

**Comment by JL2718** [comment]
Feature is functionally complete and tested for use by other modules

**Comment by JL2718** [comment]
+cargo fmt

**Comment by dlubarov** [comment]
Thanks for sending this!

There are some differences from what we were planning,
- We'd like to support lengths defined at runtime, vs const generics
- We'd like to have "batch" FFTs, where we transform each column of a matrix
- We'd like a generic trait so users can easily swap in one of several implementations (DIT, Bowers, four-step, various parallelized versions, etc)

I figured it would be hard to make all the changes to this branch, but I adapted your in-place DIT code in my branch #47, I hope that's okay. I'll revisit later to look at adapting other parts of your code like the tests.

**Pull request closed without merging**
