### PR TITLE
[challenger] Add blanket impls for mut refs on traits

### PR DESCRIPTION
**Pull request by jimpo**
The challenger traits all have methods that operate on mutable self references. It is natural to provide a blanket implementation on mutable references to challengers so that function signatures may take challenger objects instead of mutable references to them.

For example, in the `p3-commit::pcs` module the methods take a `&mut Challenger` (see https://github.com/Plonky3/Plonky3/blob/main/commit/src/pcs.rs#L52). With this code change, they could instead take a `Challenger`.

This is a common pattern in Rust. For example, there is a [similar blanket implementation implementation on `rand::RngCore`](https://docs.rs/rand/latest/rand/trait.RngCore.html#impl-RngCore-for-%26%27a%20mut%20R). This pattern is also mentioned in the section "Ergonomic Trait Implementations" in Chapter 3 of "Rust for Rustaceans".

### CODE REVIEW

**Comment by dlubarov** [comment]
Thanks for the PR! I don't have the book but it looks like the `Rng` docs discuss this a bit further,

> An alternative pattern is possible: `fn foo<R: Rng>(rng: R)`. This has some trade-offs. It allows the argument to be consumed directly without a `&mut` (which is how `from_rng(thread_rng())` works); also it still works directly on references (including type-erased references). Unfortunately within the function `foo` it is not known whether `rng` is a reference type or not, hence many uses of `rng` require an extra reference, either explicitly (`distr.sample(&mut rng)`) or implicitly (`rng.gen()`); one may hope the optimiser can remove redundant references later.

My only concern is if we start with `challenger: C`, it seems like we'd pass `&mut challenger` to sub-protocols (if the outer protocol isn't done with the challenger), possibly leading to a `&mut &mut ... challenger` chain to dereference. I wouldn't expect a ton of layers or a ton of challenger calls, so it might not be worth worrying about, but do you have thoughts on this?

**Comment by dlubarov** [comment]
Also just wondering, is there something about these challenger traits that make this pattern especially useful here, or is it more of a generic pattern that should be considered for any trait that gets used a lot?

**Comment by jimpo** [comment]
Yeah, I'm not that concerned about that (it seems like it would take a lot of dereferences to make any performance impact as compared to actually doing the hashing that the challenger ultimately performs). But perhaps it's worth adding the `#[inline(always)]` annotations like the `rand` crate does here: https://rust-random.github.io/rand/src/rand_core/lib.rs.html#400. I'm happy to do that if you agree.

As for why I think it makes sense here, it's really just an issue I encountered in binius. We set up some of our protocols to take a `mut impl Challenger` like here: https://gitlab.com/UlvetannaOSS/binius/-/blob/2789c055e41d7b49cb4132736828535f28184783/src/protocols/test_utils.rs#L93. If these methods need to pass the challenger on, they need to take a mut ref. One option is for us to change things so that every such method takes `&mut impl Challenger`. But I don't see why we should require that.

Another perspective is that the challenger is very very similar to an `Rng` (it generates pseudo-random challenges), so using it in a similar way to `Rng`, as in taking `mut R` as opposed to `&mut R`, makes sense to me. The property that these traits all have here is that all of the methods are on `&mut self`. So basically, I don't think you need to religiously apply this rule everywhere, but those are the things I think make challenger special.

**Review by dlubarov — APPROVED** [review]
Thanks for the extra context, sounds reasonable to me!

I think `#[inline(always)]` couldn't hurt, I can add it after merging. We could still end up with chains to dereference, but yeah it's probably insignificant especially if we're guaranteed no extra function call overhead.

**Pull request merged**
