### PR TITLE
Lazily compute twiddles

### PR DESCRIPTION
**Pull request by dlubarov**
In `Radix2Dit` for now; if we're happy with this style we can do it for others.

### CODE REVIEW

**Comment by dlubarov** [comment]
The twiddles for different sizes are redundant with one another, but I think it may be best to store them with this redundancy for the sake of cache friendliness, i.e. so that the twiddles for a particular size are stored contiguously.

**Comment by rjeli** [comment]
So, I get why you're doing `Vec<Vec<F>>` instead of just `Vec<F>` - the latter might work for something that wants bit-reversed twiddles, but this seems the best for this DFT

But I don't get why you compute the smaller twiddles? They don't get used in the currently executing DFT, right? Maybe a `Vec<Option<Vec<F>>` or even a `BTreeMap<usize, Vec<F>>` would be better?

Furthermore, if you *were* to compute the smaller twiddles, you could just copy it from a stride of the larger twiddle. Possibly worth moving the logic into a `PrecomputedTwiddles` that the `Dft` impls can all use (as a field, not actually sharing the twiddles at runtime)

**Comment by dlubarov** [comment]
Yeah true, smaller ones aren't necessarily needed, I'll try the `Vec<Option<Vec<F>>>` approach

**Comment by dlubarov** [comment]
Ran into some complications with `Vec<Option<Vec<F>>>`, maybe `BTreeMap` is the better route. Might be a bit of extra memory traversal, but it's probably negligible, and the code is the cleanest.

**Review by rjeli — APPROVED** [review]
LGTM

**Pull request merged**
